Sd add associated party r5
ansforge/IG-fhir-essais-cliniques pull request #123
Opened 2024-02-12 16:08 UTC by sdemeyANS

## Description des changements

voir issue https://github.com/ansforge/IG-fhir-essais-cliniques/issues/113

## Preview

https://ansforge.github.io/IG-fhir-essais-cliniques/ig/sd-add-associatedPartyR5/artifacts.html

## Impact API ECLAIRE
Oui voir issue

2024-02-13 08:28 UTC, nriss commented on input/fsh/CodeSystem/EclaireStudyPartyOrganizationTypeCS.fsh
> +Title: "Définition des différents types d'organisation des parties prenantes inspiré de https://hl7.org/fhir/codesystem-research-study-party-organization-type.html"
Peut-être mettre l'url canonique plutôt que l'adresse avec le ".html" ?

2024-02-13 08:31 UTC, nriss approved these changes

2024-02-16 11:08 UTC, sly-kereval requested changes

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/StructureDefinition/extensions/ECLAIREassociatedPartyR5.fsh
> +* extension[name] ^short = "Nom du partie prenante / Name of associated party"
Nom de la partie prenante ?

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/CodeSystem/EclaireStudyPartyRoleCS.fsh
> +* #ethics "Ethics Review Board" "Ethics Review Board"
C'est normal que la description des codes soit répétée ?

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/CodeSystem/EclaireStudyPartyOrganizationTypeCS.fsh
> +Description: "Différents rôles des parties impliqués dans l'essai"
impliquées

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/CodeSystem/EclaireStudyPartyRoleCS.fsh
> +Description: "Différents rôles des parties impliqué dans l'essai"
impliquées

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/StructureDefinition/extensions/ECLAIREassociatedPartyR5.fsh
> +* extension[party] ^short = "Structured outcome definition / Individual or organization associated with study (use practitionerRole to specify their organisation)"
C'est normal le "Structured outcome definition" ?

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/ValueSet/EclaireStudyPartyRoleVS.fsh
> +Description: "Value Set Eclaire pour les différents rôles des parties impliqués dans l'essai cliniques (sponsor, collaborateur, etc)."
impliquées

2024-02-16 11:08 UTC, sly-kereval commented on input/fsh/ValueSet/EclaireStudyPartyOrganizationTypeVS.fsh
> +Description: "Value Set Eclaire pour les types de parties impliqués dans l'essai."
impliquées

2024-02-16 15:23 UTC, sly-kereval approved these changes

2024-02-16 15:36 UTC, merged