Sd suppr extension eclaire condition details and new slice
ansforge/IG-fhir-essais-cliniques pull request #70
Opened 2023-10-05 16:41 UTC by sdemeyANS

proposition de traitment de l'issue https://github.com/ansforge/IG-fhir-essais-cliniques/issues/51

- suppression de l'extension eclaire-condition-details
- creation slice sur condition
- modification du mapping FHIR en conséquence

2023-10-05 16:44 UTC, sdemeyANS commented
@paulineheurtebise et @sly-kereval  il y a des conflits sur input/images-source/mapping.txt
input/images/mappingResearchStudy.svg :(

2023-10-06 07:10 UTC, sly-kereval approved these changes

2023-10-06 12:46 UTC, nriss requested changes

2023-10-06 12:46 UTC, nriss commented on input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh
> +* condition ^slicing.discriminator.path = "id"
Il faut fixer l'id des slices si tu utilises l'id comme discriminator

2023-10-06 19:41 UTC, sdemeyANS commented on input/fsh/StructureDefinition/profiles/ECLAIREResearchStudy.fsh
> +* condition ^slicing.discriminator.path = "id"
exact

2023-10-09 08:41 UTC, nriss approved these changes

2023-10-09 13:16 UTC, merged